spring.application.name=ExpenseSplitter
spring.datasource.url=jdbc:h2:file:./data/expense_splitter_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keep the app running even without web environment
# Enable web environment for REST APIs
spring.main.web-application-type=servlet

# Application Settings
app.currency.code=INR
app.currency.symbol=\u20B9
