package com.malcolm.expensesplitter;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.stage.Stage;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import atlantafx.base.theme.PrimerDark;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import java.util.List;
import java.util.Map;

/**
 * Main Entry point for the Expense Splitter Pro application.
 * Integrates Spring Boot with JavaFX to provide a powerful desktop experience
 * with transactional database support and modern UI styling.
 */
@SpringBootApplication
public class ExpenseSplitterApplication extends Application {

    private static ConfigurableApplicationContext context;
    private static String[] savedArgs;

    public static void main(String[] args) {
        savedArgs = args;
        Application.launch(ExpenseSplitterApplication.class, args);
    }

    @Override
    public void init() throws Exception {
        context = SpringApplication.run(ExpenseSplitterApplication.class, savedArgs);
        context.getAutowireCapableBeanFactory().autowireBean(this);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Set modern theme
        Application.setUserAgentStylesheet(new PrimerDark().getUserAgentStylesheet());

        // Load main FXML using Spring factory
        javafx.fxml.FXMLLoader loader = new javafx.fxml.FXMLLoader(getClass().getResource("/fxml/dashboard.fxml"));
        loader.setControllerFactory(context::getBean);
        javafx.scene.Parent root = loader.load();

        javafx.scene.Scene scene = new javafx.scene.Scene(root, 1024, 768);
        scene.getStylesheets().add(getClass().getResource("/css/styles.css").toExternalForm());

        primaryStage.setScene(scene);
        primaryStage.setTitle("Expense Splitter Pro");
        primaryStage.show();
    }

    @Override
    public void stop() throws Exception {
        context.close();
        Platform.exit();
    }

    /**
     * Self-healing logic to drop restrictive Enum check constraints generated by Hibernate.
     * This is necessary when adding new Enum values (like EXACT, SHARES) to an existing H2 database.
     */
    @Bean
    public CommandLineRunner fixDatabaseConstraints(JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                // Find all check constraints on the 'expenses' table
                // We check multiple metadata tables to support both H2 v1.4 and v2.x
                String[] queries = {
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINTS WHERE TABLE_NAME = 'EXPENSES' AND CONSTRAINT_TYPE = 'CHECK'",
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'EXPENSES' AND CONSTRAINT_TYPE = 'CHECK'",
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINTS WHERE TABLE_NAME = 'expenses' AND CONSTRAINT_TYPE = 'CHECK'",
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'expenses' AND CONSTRAINT_TYPE = 'CHECK'"
                };
                
                for (String sql : queries) {
                    try {
                        List<Map<String, Object>> constraints = jdbcTemplate.queryForList(sql);
                        for (Map<String, Object> constraint : constraints) {
                            String constraintName = (String) constraint.get("CONSTRAINT_NAME");
                            System.out.println("Self-healing: Found check constraint: " + constraintName + " (via " + sql + ")");
                            try {
                                jdbcTemplate.execute("ALTER TABLE EXPENSES DROP CONSTRAINT " + constraintName);
                                System.out.println("Self-healing: Successfully dropped " + constraintName);
                            } catch (Exception e) {
                                // Try lowercase table name just in case
                                try {
                                    jdbcTemplate.execute("ALTER TABLE expenses DROP CONSTRAINT " + constraintName);
                                } catch (Exception e2) {
                                    System.err.println("Self-healing: Failed to drop " + constraintName + ": " + e2.getMessage());
                                }
                            }
                        }
                    } catch (Exception e) {
                        // Some tables might not exist in all H2 versions, ignore
                    }
                }

                // Ensure legacy paid_by_id is nullable in the actual schema
                System.out.println("Self-healing: Ensuring PAID_BY_ID is nullable...");
                jdbcTemplate.execute("ALTER TABLE EXPENSES ALTER COLUMN PAID_BY_ID SET NULL");
            } catch (Exception e) {
                // If the table doesn't exist yet or other issue, ignore
                System.err.println("Database healing skipped: " + e.getMessage());
            }
        };
    }
}
